name: Build Overmind main.js

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - run: npm install --no-audit --no-fund --no-package-lock --legacy-peer-deps
      - run: npm run compile
      - name: Collect build artifacts
        run: |
          mkdir -p dist
          if [ -f main.js ]; then
            cp main.js dist/main.js
          elif [ -f build/main.js ]; then
            cp build/main.js dist/main.js
          fi
          ls -lah dist
      - name: Commit dist/main.js
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: build main.js from ${{ github.sha }}"
          file_pattern: dist/main.js
